# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CryptoEvents_pb2 as CryptoEvents__pb2


class CryptoNotifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLatestCandle = channel.unary_unary(
                '/cryptoevents.CryptoNotifier/getLatestCandle',
                request_serializer=CryptoEvents__pb2.CandleRequest.SerializeToString,
                response_deserializer=CryptoEvents__pb2.CandleResponse.FromString,
                )


class CryptoNotifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLatestCandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CryptoNotifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLatestCandle': grpc.unary_unary_rpc_method_handler(
                    servicer.getLatestCandle,
                    request_deserializer=CryptoEvents__pb2.CandleRequest.FromString,
                    response_serializer=CryptoEvents__pb2.CandleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryptoevents.CryptoNotifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CryptoNotifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLatestCandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cryptoevents.CryptoNotifier/getLatestCandle',
            CryptoEvents__pb2.CandleRequest.SerializeToString,
            CryptoEvents__pb2.CandleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
