# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CryptoEvents.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CryptoEvents.proto',
  package='cryptoevents',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x43ryptoEvents.proto\x12\x0c\x63ryptoevents\"D\n\rCandleRequest\x12%\n\x06ticker\x18\x01 \x01(\x0e\x32\x15.cryptoevents.Tickers\x12\x0c\n\x04pair\x18\x02 \x01(\t\"H\n\x0e\x43\x61ndleResponse\x12\x0c\n\x04open\x18\x01 \x01(\x02\x12\x0c\n\x04high\x18\x02 \x01(\x02\x12\x0b\n\x03low\x18\x03 \x01(\x02\x12\r\n\x05\x63lose\x18\x04 \x01(\x02*.\n\x07Tickers\x12\x07\n\x03t1m\x10\x00\x12\x07\n\x03t5m\x10\x01\x12\x08\n\x04t15m\x10\x02\x12\x07\n\x03t1h\x10\x03\x32`\n\x0e\x43ryptoNotifier\x12N\n\x0fgetLatestCandle\x12\x1b.cryptoevents.CandleRequest\x1a\x1c.cryptoevents.CandleResponse\"\x00\x62\x06proto3'
)

_TICKERS = _descriptor.EnumDescriptor(
  name='Tickers',
  full_name='cryptoevents.Tickers',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='t1m', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='t5m', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='t15m', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='t1h', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=180,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_TICKERS)

Tickers = enum_type_wrapper.EnumTypeWrapper(_TICKERS)
t1m = 0
t5m = 1
t15m = 2
t1h = 3



_CANDLEREQUEST = _descriptor.Descriptor(
  name='CandleRequest',
  full_name='cryptoevents.CandleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='cryptoevents.CandleRequest.ticker', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pair', full_name='cryptoevents.CandleRequest.pair', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=104,
)


_CANDLERESPONSE = _descriptor.Descriptor(
  name='CandleResponse',
  full_name='cryptoevents.CandleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='open', full_name='cryptoevents.CandleResponse.open', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='cryptoevents.CandleResponse.high', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='cryptoevents.CandleResponse.low', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close', full_name='cryptoevents.CandleResponse.close', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=178,
)

_CANDLEREQUEST.fields_by_name['ticker'].enum_type = _TICKERS
DESCRIPTOR.message_types_by_name['CandleRequest'] = _CANDLEREQUEST
DESCRIPTOR.message_types_by_name['CandleResponse'] = _CANDLERESPONSE
DESCRIPTOR.enum_types_by_name['Tickers'] = _TICKERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CandleRequest = _reflection.GeneratedProtocolMessageType('CandleRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANDLEREQUEST,
  '__module__' : 'CryptoEvents_pb2'
  # @@protoc_insertion_point(class_scope:cryptoevents.CandleRequest)
  })
_sym_db.RegisterMessage(CandleRequest)

CandleResponse = _reflection.GeneratedProtocolMessageType('CandleResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANDLERESPONSE,
  '__module__' : 'CryptoEvents_pb2'
  # @@protoc_insertion_point(class_scope:cryptoevents.CandleResponse)
  })
_sym_db.RegisterMessage(CandleResponse)



_CRYPTONOTIFIER = _descriptor.ServiceDescriptor(
  name='CryptoNotifier',
  full_name='cryptoevents.CryptoNotifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=228,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLatestCandle',
    full_name='cryptoevents.CryptoNotifier.getLatestCandle',
    index=0,
    containing_service=None,
    input_type=_CANDLEREQUEST,
    output_type=_CANDLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRYPTONOTIFIER)

DESCRIPTOR.services_by_name['CryptoNotifier'] = _CRYPTONOTIFIER

# @@protoc_insertion_point(module_scope)
